### PR TITLE
bump golang.org/x/tools so things work with 1.18

### PR DESCRIPTION
**Pull request by chipaca**
1.18 needs an updated golang.org/x/tools, otherwise it's #48 all over again.

### CODE REVIEW

**Comment by ekle** [comment]
Works fine here.

**Comment by chipaca** [comment]
@ekle do you mean this PR fixes the issue, or that there is no issue to begin with?

**Comment by ekle** [comment]
This PR fixes the issue for me.

**Comment by mvdan** [comment]
Friendly ping @mdempsky :) I would happily help review and merge changes to keep the tool working if you'd like any help.

**Comment by mdempsky** [comment]
@mvdan Thanks, I've invited you as a collaborator.

**Pull request merged**
