### PR TITLE
Exit with non-zero code if we reported conversions

### PR DESCRIPTION
**Pull request by dominikh**
Closes gh-5

### CODE REVIEW

**Comment by dominikh** [comment]
@mdempsky  Do you want me revise the PR, or is it easier for you to just write it yourself at this point?

**Comment by dominikh** [comment]
Updated the PR.

**Comment by mdempsky** [comment]
Easier if all I have to do is a click a button. :)

Gross that it ended up as a merge commit, rather than a fast forward.  Is that fundamental to GitHub PRs, or can I avoid that somehow?  (I'm more used to Gerrit.)

**Comment by dominikh** [comment]
It is fundamental of GitHub PRs. The merge button always creates a merge commit.

**Comment by mdempsky** [comment]
That sucks.  Oh well.

Thanks!

**Comment by shurcooL** [comment]
> The merge button always creates a merge commit.

> That sucks. Oh well.

For posterity, this has since changed. It used to be true for many years, but it's no longer true as of a few months ago. GitHub now has a "squash" merge mode that rebases and squashes into a single commit when merging.

See https://github.com/blog/2141-squash-your-commits.

**Comment by mdempsky** [comment]
Yep, I've started using that!

**Pull request merged**
